# Generated by Django 4.1.1 on 2022-11-23 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='game_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('game_video1', models.FileField(upload_to='upload/game/videos')),
                ('game_video2', models.FileField(upload_to='upload/game/videos')),
                ('game_avatar', models.ImageField(upload_to='upload/game/images')),
                ('game_images', models.ImageField(upload_to='upload/game/images')),
                ('game_type', models.CharField(choices=[('free', 'free'), ('paid', 'paid')], default=False, max_length=4)),
                ('game_amt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Userone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default=False, upload_to='upload/user/images')),
            ],
        ),
        migrations.CreateModel(
            name='spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spam', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('game_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game_details')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.userone')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('reply_review', models.CharField(default=0, max_length=100)),
                ('game_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game_details')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.userone')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=100)),
                ('card_number', models.IntegerField()),
                ('card_cvc', models.IntegerField()),
                ('card_year', models.CharField(max_length=100)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.userone')),
                ('game_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game_details')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbacks', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.userone')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.userone')),
            ],
        ),
    ]
