# Generated by Django 4.1.1 on 2022-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_details_game_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_details',
            name='game_avatar',
            field=models.ImageField(upload_to='upload/game/images'),
        ),
        migrations.AlterField(
            model_name='game_details',
            name='game_images',
            field=models.ImageField(upload_to='upload/game/images'),
        ),
        migrations.AlterField(
            model_name='game_details',
            name='game_video1',
            field=models.FileField(upload_to='upload/game/videos'),
        ),
        migrations.AlterField(
            model_name='game_details',
            name='game_video2',
            field=models.FileField(upload_to='upload/game/videos'),
        ),
    ]
