# Generated by Django 4.1.1 on 2022-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_details_game_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_details',
            name='game_file',
            field=models.FileField(default=True, upload_to='upload/game/file'),
        ),
    ]
