# Generated by Django 4.1.1 on 2022-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_applyform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userone',
            name='avatar',
            field=models.ImageField(default=True, upload_to='upload/user/images'),
        ),
    ]
