# Generated by Django 4.1.1 on 2022-12-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_userone_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='spam',
        ),
    ]
